addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 92a08281-ff5e-4045-aac1-0eab2fbcbf54
after_success: [./df-build.sh]
jdk: [oraclejdk7, openjdk7, openjdk6]
language: java
# Modified by Insights Service at 2016-03-22 12:06:19.652193
