addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 8e0ef13f-ae76-4e5b-8724-1ab0244c5c4e
after_success: [./df-build.sh]
jdk: [oraclejdk7, openjdk7, openjdk6]
language: java
# Modified by Insights Service at 2016-03-17 08:45:14.169709
